// supabase calls, actually focus on interface rather than implementation

import 'package:blog_app/core/error/exceptions.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

abstract interface class AuthRemoteDataSource {
  Future<String> signUpWithEmailPassword({
    required String name,
    required String email,
    required String password,
  });
  Future<String> loginWithEmailPassword({
    required String email,
    required String password,
  });
}

class AuthRemoteDataSourceImpl implements AuthRemoteDataSource {
  final SupabaseClient supabaseClient;
  AuthRemoteDataSourceImpl(this.supabaseClient);

  @override
  Future<String> loginWithEmailPassword({
    required String email,
    required String password,
  }) {
    // TODO: implement loginWithEmailPassword
    throw UnimplementedError();
  }

  @override
  Future<String> signUpWithEmailPassword({
    required String name,
    required String email,
    required String password,
  }) async {
    try {
      // masukan data user ke supabase
      final response = await supabaseClient.auth.signUp(
        password: password,
        email: email,
        data: {'name': name}, // key, value; Map<String, dynamic>
      );

      // kalo user null
      if (response.user == null) {
        throw const ServerException('User is null');
      }

      // return user id generated by supabase
      return response.user!.id;
    } catch (e) {
      throw ServerException(e.toString());
    }
  }
}
